### ISSUE TITLE
Displaying a fixed time

### ISSUE THREAD

**Issue by aklodhi98** [simonbaird/CoolClock#14]
This is more a question than an issue with the script.

What I need to do is to hook up the clock display with a pre-configured database, so that it displays specific times as read from the database. For example, the clock would need to display 6pm this week, and 7pm next week. Could you give me a few pointers on how to go about this?

**Comment by henrahmagix** [comment]
The following should do it:

``` javascript
$(function() {
    // Create a clock in the available canvas. This starts it ticking.
    // <canvas id="static-clock"></canvas>
    var staticClock = new CoolClock({
        canvasId: 'static-clock'
    });
    // Stop the clock.
    staticClock.stop();
    // Render a specific time: 1:35pm
    var hour = 13;
    var minute = 35;
    var second = 0;
    staticClock.render(hour, minute, second);
});
```

Replace the `hour`, `minute`, and `second` variables with the time values from the database =)

**Comment by aklodhi98** [comment]
Thanks for this, forking to try it out.
